### ISSUE TITLE
Improvements for documentation

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/exasol-testcontainers#10]
Here is the list of problems I encountered and didn't find information in documentation:

1. Specify the format of path for `uploadFile`, `listContents` etc. The path should be written without slash(/) at the beginning. The `pathInBucket` for `uploadFile` should include the files' name in the bucket.
2. Add information that creating a new bucket is not supported yet.

**Comment by redcatbear** [comment]
Added section "Specifying 'Paths' Inside a Bucket".
Mentioned that creating and deleting buckets and services is not yet supported.
