### ISSUE TITLE
Improve `uploadFile`'s  exceptions

### ISSUE THREAD

**Issue by jakobbraun** [exasol/exasol-testcontainers#104]
As a user I don't know what do do if a `InterruptedException` occurs during `uploadFile`.
If I should implement a retry, that should be done in the `uploadFile` method.

I would prefer a single UploadFailed exception if the upload failed and retry makes no sense.
Having these three different exceptions (`InterruptedException`, `BucketAccessException`, `TimeoutException`) does not add value here. In all cases, I have to abort the test.

Especially the interrupted exception is a problem [sonar does not like if I catch it](https://rules.sonarsource.com/java/tag/multi-threading/RSPEC-2142) like:

```java
try {
      bucket.uploadFile(JACOCO_AGENT_PATH, JACOCO_AGENT_NAME);
} catch (final InterruptedException | TimeoutException | BucketAccessException exception) {
      throw new IllegalStateException(
          ExaError.messageBuilder("E-UDJ-3").message("Failed to upload jacoco agent to BcuektFS.").toString(),
               exception);
}
```

**Comment by redcatbear** [comment]
`InterruptedExceptions` are special. You cannot just catch them and be done. If you just catch an `InterruptedException`, you reset the interrupt state. You always need to set that back by hand before throwing a new exception. That is what SONAR really complains about.
https://dzone.com/articles/how-to-handle-the-interruptedexception

So as annoying as the current situation might be, it makes sense.
