### ISSUE TITLE
java.sql.SQLException: BucketFS: File '/exaudf/exaudfclient' does not exist

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/exasol-testcontainers#12]
## Problem

While using the framework I encountered the problem which is described here:
https://github.com/EXASOL/docker-db/issues/2

How to reproduce:

...
1. statement.execute("CREATE CONNECTION")
2. statement.execute("CREATE OR REPLACE JAVA ADAPTER SCRIPT")
3. statement.execute("CREATE VIRTUAL SCHEMA") -> it comes from this line.
...

It's currently 'fixed' with `sleep`:
...
1. statement.execute("CREATE CONNECTION")
2. statement.execute("CREATE OR REPLACE JAVA ADAPTER SCRIPT")
TimeUnit.SECONDS.sleep(20); 
3. statement.execute("CREATE VIRTUAL SCHEMA") -> it comes from this line.
...

15 seconds of sleep is still not enough, but it wasn't reproduces with 20 seconds.

**Comment by redcatbear** [comment]
The apparent problem here is that at the moment we don't wait until the UDF container is fully unpacked. While that does not matter in cases where UDF is not used, it obviously hurts tests where we need the UDF infrastructure.
