### ISSUE TITLE
Make class ExasolDatabaseCleaner public

### ISSUE THREAD

**Issue by YotillaMarco** [exasol/exasol-testcontainers#126]
I would like to use the class [`ExasolDatabaseCleaner`](https://github.com/exasol/exasol-testcontainers/blob/main/src/main/java/com/exasol/containers/ExasolDatabaseCleaner.java) in my project. Therefor I kindly request to make this class `public`.

**Comment by jakobbraun** [comment]
I'm moving this to a seperate repo
