### ISSUE TITLE
Add support for docker network for reuse

### ISSUE THREAD

**Issue by morazow** [exasol/exasol-testcontainers#128]
### Situation

Testcontainers reuse mechanism does not work if the container is attached to a network. See: https://github.com/testcontainers/testcontainers-java/pull/1781 (Challenges Ahead).

For time being we can support a named docker network from the exasol-testcontainers. We already have two projects that use Exasol containers with networks.

### Acceptance Criteria

- Named docker network class is added (from [DockerNamedNetwork](https://github.com/exasol/spark-exasol-connector/blob/main/src/it/scala/com/exasol/spark/DockerNamedNetwork.scala))
- Unit and integration tests are added

**Comment by redcatbear** [comment]
No capacity.
