### ISSUE TITLE
Upgrade to Exasol 8.0

### ISSUE THREAD

**Issue by kaklakariada** [exasol/exasol-testcontainers#192]
Links to https://github.com/exasol/roadmap/issues/76 

When Exasol 8.0 is available on docker hub, we need to upgrade exasol-testcontainers to use the new release in order to verify everything works with the new release.

Branch for the upgrade already exists: https://github.com/exasol/exasol-testcontainers/tree/feature/%23191-support-exasol-8

## Acceptance criteria
* [ ] All tests are green

**Comment by ckunki** [comment]
Changing ExasolContainerConstants to 
```java
    public static final String EXASOL_DOCKER_IMAGE_VERSION = "8.0.4";
```
runs DatabaseServiceIT successful.

**Comment by ckunki** [comment]
Currently Testcase BucketIT after some seconds and then hangs in the setup phase

```java
@Container
private static final ExasolContainer<? extends ExasolContainer<?>> container = new ExasolContainer<>() //
   .withLogConsumer(new Slf4jLogConsumer(LOGGER));
```

The last displayed log message is
```
2022-08-10 16:03:25.360 [INFO   ] STDOUT: [2022-08-10 14:03:25 +00:00] root child 285 (exainit.py) returned with state 0.
```

Lowering the log level to ALL shows
```
2022-08-10 15:30:14.435 [FINE   ] http-outgoing-29 <<
"{"ID":"f89c2c7b0deda9108d954c919262cdaf95f396aed671d1c5b77bddedee480dee",
  "Running":false, "ExitCode":0, "ProcessConfig": {
    "tty":false,
    "entrypoint":"find",
    "arguments":[
      "/exa/logs/cored", "-name", "bucketfsd.*.log", "-exec", "awk",
      "/ScriptLanguages.*extracted$/{a=$0}END{print a}",
      "{}", "+" ], "privileged":false
  },
  "OpenStdin":false, "OpenStderr":true, "OpenStdout":true, "CanRemove":false,
  "ContainerID":"a5b79acc4f3778f4463e8ef270aed6c890621accd3ca745aace473a237ef7968",
  "DetachKeys":"", "Pid":3257}[\n]"
```

See also class UdfContainerWaitStrategy:
```java
SCRIPT_LANGUAGE_CONTAINER_READY_PATTERN = "ScriptLanguages.*extracted$";
```

My interpretation is that test setup searches file `/exa/logs/cored/bucketfsd.*.log` for a line matching regex `ScriptLanguages.*extracted$`.

In contrast logfile `/exa/logs/cored/bucketfsd.325.16.0.480.log` only contains 3 lines shown below, which does not fulfil the matching criteria:
```
[I 220810 13:34:05 bucketfsd:754] RSYNC THREAD started
[I 220810 13:34:05 bucketfsd:1506] UNPACK THREAD started
[I 220810 13:34:05 bucketfsd:2325] bfsdefault server started in rsync mode.
```

Questions and open issues
* Should we change the strategy to identify UDF startup to be finished?

**Comment by ckunki** [comment]
#### Strategy for validation of existing test cases in exasol-testcontainers with Exasol version 8.0: 

| Status | Folder | Comment	 |
|--------|--------|----------|
| :grey_question: | bucketfs | has probably changed: try |
| :heavy_check_mark: | clusterlogs | should be successful |
| :heavy_check_mark: | config | should be successful | |
| :grey_question: | containers | status unknown |
| :heavy_check_mark: | database | should be successful |
| :heavy_check_mark: | drivers | convenience interface to install drivers in bucketfs, should be ok |
| :heavy_check_mark: | exaconf | should be successful |
| :x: | exaoperation | <ul> <li>not provided by Exa 8 anymore</li> <li>use conditional test execution with assumption version < 8</li> <li>see junit 5 "ASSUME"</li> </ul> |
| :x: | support | risky, won't work on windows |

**Comment by ckunki** [comment]
Problem with logs was caused by multiple docker instances running and manual analysis was in the wrong instance.

**Comment by ckunki** [comment]
Current observation: timestamp format of log file entries apparently has changed:
```
[I 220811 13:32:40 bucketfsd:219] rsync for id (('bfsdefault', 'default', 'test-uploaded.txt')) is done
```

**Comment by ckunki** [comment]
Maybe this project, but potentially also bucketfs-java needs to be enhanced to test Exasol version 8 as well. 
Will there be a docker image available?

**Comment by ckunki** [comment]
Using docker image 8.0.4-oldstyle-virtualschemadatatypes-SPOT-14652 and bucketfs-java version 2.3.0 `mvn verify` in my Linux vm now terminates with success. 
Completing the current ticket now needs to wait for an appropriate docker image to be available.
