### ISSUE TITLE
Allow enabling TLS for BucketFS

### ISSUE THREAD

**Issue by kaklakariada** [exasol/exasol-testcontainers#234]
By default docker-db does not enable TLS for BucketFS, see this default `/exa/etc/EXAConf` (for both Exasol 7.1 and 8):

```
[BucketFS : bfsdefault]
    Owner = 500 : 500
    # HTTP port number (0 = disabled)
    HttpPort = 2580
    # HTTPS port number (0 = disabled)
    HttpsPort = 0
```

In order to test behavior with TLS (e.g. https://github.com/exasol/bucketfs-client/issues/33) we need to allow enabling TLS for BucketFS when starting a new container.

A possible solution could be using [confd](https://docs.exasol.com/db/latest/confd/confd.htm) job [bucketfs_modify](https://docs.exasol.com/db/latest/confd/jobs/bucketfs_modify.htm):
```sh
confd_client -c bucketfs_modify -a '{"bucketfs_name": "bucketfs1", "http_port": 0, "https_port": 2581, "owner": [500, 500]}'
```

**Comment by redcatbear** [comment]
This is only relevant for 7.1. In 8 this is not active by default, so we won't invest time into this anymore.
