### ISSUE TITLE
Emulate installation and start of EXAsolution plug-in

### ISSUE THREAD

**Issue by redcatbear** [exasol/exasol-testcontainers#33]
## Situation

EXAoperation is not included in the [`docker-db`](https://github.com/exasol/docker-db). If we plan to test an EXAoperation plug-in that means, we need a workaround for the missing parts.

## Acceptance Criteria

1. Installation of an EXAoperation plug-in can be done without EXAoperation through the test container
2. The plug-in can be started through the test container

**Comment by exaSR** [comment]
(EXASolution ==> EXAOperation)

**Comment by redcatbear** [comment]
Corrected names.
