### ISSUE TITLE
Option to skip waiting for UDF container

### ISSUE THREAD

**Issue by redcatbear** [exasol/exasol-testcontainers#35]
## Situation

If the test conducted with the Exasol-Testcontainer do not include User Defined Functions (UDFs), the tester can skip waiting for the UDF container to become ready and save some time in the test setup.

## Acceptance Criteria

1. User can configure the test container so that waiting for the UDF container to be ready can be skipped.

**Comment by exaSR** [comment]
I guess this may break existing tests, but would it be possible to implement "no containers" as default, and add `withContainer(...)` and/or `withBucket(...)` methods to the ExasolContainer?
