### ISSUE TITLE
Improve JDBC driver documentation

### ISSUE THREAD

**Issue by redcatbear** [exasol/exasol-testcontainers#41]
## Situation

In the user guide we mention JDBC 6.0.0. A newer version is preferable. Also a hint would be helpful that the driver needs to be loaded from the Exasol Artifactory.

```
  <repositories>
    <repository>
      <id>maven.exasol.com</id>
      <url>https://maven.exasol.com/artifactory/exasol-releases</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
  </repositories>
```

## Acceptance Criteria

1. Documentation updated

**Comment by exaSR** [comment]
Actually, the driver seems to be available on [maven central](https://mvnrepository.com/artifact/com.exasol/exasol-jdbc)

**Comment by redcatbear** [comment]
Exactly. This search engine is not the same as the Central Repository.
Check: https://search.maven.org/search?q=exasol-jdbc
