### ISSUE TITLE
DatabaseService::start() does not wait until database is connectible

### ISSUE THREAD

**Issue by exaSR** [exasol/exasol-testcontainers#56]
After calling `DatabaseService::start`, `Container::getJdbcConnection`may still produce a `connection refused`error if the test is too quick.

### Expected behavior
`start`returns when the database is usable, or throws an Exception.

Easiest way to do so would probably be to call `JdbcDatabaseContainer::waitUntilContainerStarted` internally.

**Comment by exaSR** [comment]
*Update:* Might have been a red herring tracing another problem in my test code... will keep an eye on it.

**Comment by exaSR** [comment]
Actually, `JdbcDatabaseContainer::waitUntilContainerStarted` is buggy insofar it does support a startupTimeout and logs "container started" after the timeout, even when the database is not reachable yet.

**Comment by redcatbear** [comment]
On it. Thanks for reporting this!
