### ISSUE TITLE
Add automated test for windows

### ISSUE THREAD

**Issue by jakobbraun** [exasol/exasol-testcontainers#86]
## Situation

Exasol Testcontainers were originally written to be used under Linux. We have people using them under Windows now too, so the automated tests should be run there too.

## Acceptance Criteria

* Additional Windows CI test set up in GHA test matrix
* Failing tests fixed or unavailable features disabled on Windows

**Comment by pj-spoelders** [comment]
https://github.com/testcontainers/testcontainers-java/issues/2960 On both travis CI and github the runners are 'windows server 2019' or the 2016 version ..
It does run quite well on Windows 10 pro.
There was one test that needed to be fixed. At the moment I will just 'park' this ticket and come back to it later.

**Comment by pj-spoelders** [comment]
After a brief discussion, @tkilias suggested looking into dedicated machines (costly) or VMs that allow nested virtualisation. 
Linux containers on Windows docker require a VM (which WSL2 is and how docker desktop solves it).
We need to look into self-hosted runners anyway (for our UI automation tests) so this is another project that's probably going to need this. Apparently the 'script language tool' would be another candidate.

**Comment by pj-spoelders** [comment]
There are also still some errors when I run the extended integration tests so I also need to get back to these.

**Comment by pj-spoelders** [comment]
https://www.testcontainers.org/supported_docker_environment/windows/

**Comment by pj-spoelders** [comment]
Current issues:

- Github actions does not allow/support docker/container operations on windows runners at the moment: 
 https://github.com/actions/runner/issues/904

- Other options left would be to use a self hosted runner or azure devops runner. Problems here are:
  - Added maintenance and security risk.
  - You'd need a docker desktop enterprise license for running linux containers (in our case exasol docker-db and others) in a windows environment. Java-testcontainers, the main dependency of exasol-testcontainers, depends on docker desktop.
  - WSL2 depends on a VM for linux containers, which requires virtualisation. Virtualisation is also quite tricky to find and get right (limited support) and expensive to set up in the cloud.
  - WSL1 might bring its own share of issues. Also windows server (which comes only with WSL1) is not supported and there's no real mention of WSL1 in the windows support information.
