### ISSUE TITLE
Using the lowest version is unituitive

### ISSUE THREAD

**Issue by jakobbraun** [exasol/exasol-testcontainers#89]
If you now use ExasolTestContainer("7") image version 7.0.0 is used. Not the latest.
For a user's perspective one would expect that the the latest version is used.

**Comment by redcatbear** [comment]
In tests you should always pin versions. Picking latest automatically is never safe.

**Comment by exaSR** [comment]
@redcatbear: True. But given the estimated release cycles in my project vs. its dependencies, I need to make sure that no problems appear when dependencies get updated on customer side -- Without any commit to my respository.

Also -- testcontainers are a pretty nifty way to fire up an Exasol Community Edition :)

**Comment by redcatbear** [comment]
New idea. How about allowing the following extension.

A new constructor, where you can set a flag that you want to have the latest that starts with that version:

```java
ExasolTestContainer fixed = new ExasolTestContainer("7", VERSION_RANGE.EXACT_VERSION);
// Same as existing constructor: -> 7
ExasolTestContainer anyLaterVersion = new ExasolTestContainer("7", VERSION_RANGE.LATEST_INCLUDING_THIS);
// 7, 7.1, 7.1.1, ..., 8, 8.1, ...
ExasolTestContainer sevenAndSevenX = new ExasolTestContainer("7", VERSION_RANGE.LASTEST_POSTFIX_VERSION);
// 7, 7.1, 7.1.1, 7.2
```

The trouble here being that this would require either a hard-coded and regularly updated table in the ETC or a network lookup to determine the latest version. First variant is better, since it has no external dependency. But it requires that with every new Exasol release the list is updated. Including fix releases of course.

**Comment by jakobbraun** [comment]
Or add an itnterface like:

```java
ExasolTestContainer("*");//latest existing
ExasolTestContainer("7.*.*");//latest v7
ExasolTestContainer("7.1.*");//latest v7.1
ExasolTestContainer("7.0.0");//ixed 7.0.0
```

**Comment by exaSR** [comment]
I would very much like to see the network lookup implemented in the testcontainers. It would at least give one centrally managed piece of code for it.

In the end you wouldn't even have to change the `ExasolTestContainer` signature or semantic:

```java
ExasolTestContainer( getExasolRelease("6.2", LATEST) ); // 6.2.9 known to testcontainers
ExasolTestContainer( getExasolRelease("6.2", ONLINE) ); // 6.2.10 released after testcontainers
```

**Comment by jakobbraun** [comment]
In discussion with @redcatbear we decided to implement this feature in a separate repository: exasol-version-number-provider
This new provider will for example allow you to:
* Get the latest released version
* Get the latest release version for a fixed major version
* Get all supported versions (for matrix tests)
* Get all versions

**Comment by jakobbraun** [comment]
implemented at https://github.com/exasol/exasol-version-number-provider
